export type ListaRacasCachorros = {
  [key: string]: string;
};

export const listaRacasCachorros: ListaRacasCachorros = {
  "Akita": "Akita",
  "BassetHound": "Basset Hound",
  "Beagle": "Beagle",
  "BerneseMountainDog": "Bernese Mountain Dog",
  "BichonFrise": "Bichon Frise",
  "BorderCollie": "Border Collie",
  "BorderTerrier": "Border Terrier",
  "Boxer": "Boxer",
  "BulldogFrances": "Bulldog Francês",
  "BulldogIngles": "Bulldog Inglês",
  "BuldogueAmericano": "Buldogue Americano",
  "CairnTerrier": "Cairn Terrier",
  "CaneCorso": "Cane Corso",
  "CavalierKingCharlesSpaniel": "Cavalier King Charles Spaniel",
  "Chihuahua": "Chihuahua",
  "ChowChow": "Chow Chow",
  "CockerSpanielIngles": "Cocker Spaniel Inglês",
  "Collie": "Collie",
  "Dachshund": "Dachshund (Salsicha)",
  "Doberman": "Doberman",
  "DogueAlemao": "Dogue Alemão",
  "GalgoItaliano": "Galgo Italiano",
  "GoldenRetriever": "Golden Retriever",
  "Greyhound": "Greyhound",
  "JackRussellTerrier": "Jack Russell Terrier",
  "LabradorRetriever": "Labrador Retriever",
  "LhasaApso": "Lhasa Apso",
  "LuluDaPomerania": "Lulu da Pomerânia (Spitz Alemão)",
  "Maltese": "Maltese",
  "Mastiff": "Mastiff",
  "PastorAlemao": "Pastor Alemão",
  "PastorBelga": "Pastor Belga",
  "PastorDeShetland": "Pastor de Shetland",
  "PinscherMiniatura": "Pinscher Miniatura",
  "Poodle": "Poodle",
  "PoodleGigante": "Poodle Gigante",
  "PoodleMedio": "Poodle Médio",
  "PoodleToy": "Poodle Toy",
  "Pug": "Pug",
  "Rottweiler": "Rottweiler",
  "SchnauzerGigante": "Schnauzer Gigante",
  "SchnauzerMiniatura": "Schnauzer Miniatura",
  "SetterIrlandes": "Setter Irlandês",
  "ShetlandSheepdog": "Shetland Sheepdog",
  "ShibaInu": "Shiba Inu",
  "ShihTzu": "Shih Tzu",
  "ViraLata": "Vira-lata",
  "Whippet": "Whippet",
  "YorkshireTerrier": "Yorkshire Terrier",
};
