//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHelper.API.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetHelper.API.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agendamento não encontrado..
        /// </summary>
        internal static string AgendamentoNaoEncontrado {
            get {
                return ResourceManager.GetString("AgendamentoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agendamentos não encontrados..
        /// </summary>
        internal static string AgendamentosNaoEncontrados {
            get {
                return ResourceManager.GetString("AgendamentosNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar adicionar o agendamento..
        /// </summary>
        internal static string ErroAdicionarAgendamento {
            get {
                return ResourceManager.GetString("ErroAdicionarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar editar o agendamento..
        /// </summary>
        internal static string ErroAtualizarAgendamento {
            get {
                return ResourceManager.GetString("ErroAtualizarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar deletar o agendamento..
        /// </summary>
        internal static string ErroDeletarAgendamento {
            get {
                return ResourceManager.GetString("ErroDeletarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar adicionar o agendamento. Erro: {0}.
        /// </summary>
        internal static string ExcecaoAdicionarAgendamento {
            get {
                return ResourceManager.GetString("ExcecaoAdicionarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar editar agendamento. Erro: {0}.
        /// </summary>
        internal static string ExcecaoAtualizarAgendamento {
            get {
                return ResourceManager.GetString("ExcecaoAtualizarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar deletar o agendamento. Erro: {0}.
        /// </summary>
        internal static string ExcecaoDeletarAgendamento {
            get {
                return ResourceManager.GetString("ExcecaoDeletarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar recuperar agendamento. Erro: {0}.
        /// </summary>
        internal static string ExcecaoRecuperarAgendamento {
            get {
                return ResourceManager.GetString("ExcecaoRecuperarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar recuperar agendamentos. Erro: {0}.
        /// </summary>
        internal static string ExcecaoRecuperarAgendamentos {
            get {
                return ResourceManager.GetString("ExcecaoRecuperarAgendamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar recuperar datas dos agendamentos. Erro: {0}.
        /// </summary>
        internal static string ExcecaoRecuperarDatasDosAgendamentos {
            get {
                return ResourceManager.GetString("ExcecaoRecuperarDatasDosAgendamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar recuperar agendamentos. Erro: {0}.
        /// </summary>
        internal static string ExcecaoRecuperarHorarios {
            get {
                return ResourceManager.GetString("ExcecaoRecuperarHorarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao tentar recuperar informativos. Erro: {0}.
        /// </summary>
        internal static string ExcecaoRecuperarInformativos {
            get {
                return ResourceManager.GetString("ExcecaoRecuperarInformativos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Horários marcados não encontrados..
        /// </summary>
        internal static string HorariosNaoEncontrados {
            get {
                return ResourceManager.GetString("HorariosNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informativos não encontrados..
        /// </summary>
        internal static string InformativosNaoEncontrados {
            get {
                return ResourceManager.GetString("InformativosNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agendamento adicionado com sucesso!.
        /// </summary>
        internal static string SucessoAdicionarAgendamento {
            get {
                return ResourceManager.GetString("SucessoAdicionarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agendamento alterado com sucesso!.
        /// </summary>
        internal static string SucessoAtualizarAgendamento {
            get {
                return ResourceManager.GetString("SucessoAtualizarAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Agendamento deletado com sucesso!.
        /// </summary>
        internal static string SucessoDeletarAgendamento {
            get {
                return ResourceManager.GetString("SucessoDeletarAgendamento", resourceCulture);
            }
        }
    }
}
