//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetHelper.API.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetHelper.API.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrado..
        /// </summary>
        internal static string MensagemDadoNaoEncontrado {
            get {
                return ResourceManager.GetString("MensagemDadoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrados..
        /// </summary>
        internal static string MensagemDadosNaoEncontrados {
            get {
                return ResourceManager.GetString("MensagemDadosNaoEncontrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar adicionar o {0}..
        /// </summary>
        internal static string MensagemErroAdicionar {
            get {
                return ResourceManager.GetString("MensagemErroAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar atualizar o {0}..
        /// </summary>
        internal static string MensagemErroAtualizar {
            get {
                return ResourceManager.GetString("MensagemErroAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao tentar deletar o {0}..
        /// </summary>
        internal static string MensagemErroDeletar {
            get {
                return ResourceManager.GetString("MensagemErroDeletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma exceção ao tentar adicionar {0}. Erro: {1}.
        /// </summary>
        internal static string MensagemExcecaoAdicionar {
            get {
                return ResourceManager.GetString("MensagemExcecaoAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma exceção ao tentar atualizar {0}. Erro: {1}.
        /// </summary>
        internal static string MensagemExcecaoAtualizar {
            get {
                return ResourceManager.GetString("MensagemExcecaoAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma exceção ao tentar deletar {0}. Erro: {1}.
        /// </summary>
        internal static string MensagemExcecaoDeletar {
            get {
                return ResourceManager.GetString("MensagemExcecaoDeletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu uma exceção ao tentar recuperar {0}. Erro: {1}.
        /// </summary>
        internal static string MensagemExcecaoRecuperar {
            get {
                return ResourceManager.GetString("MensagemExcecaoRecuperar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} adicionado com sucesso!.
        /// </summary>
        internal static string MensagemSucessoAdicionar {
            get {
                return ResourceManager.GetString("MensagemSucessoAdicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} atualizado com sucesso!.
        /// </summary>
        internal static string MensagemSucessoAtualizar {
            get {
                return ResourceManager.GetString("MensagemSucessoAtualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} deletado com sucesso!.
        /// </summary>
        internal static string MensagemSucessoDeletar {
            get {
                return ResourceManager.GetString("MensagemSucessoDeletar", resourceCulture);
            }
        }
    }
}
